spring:
  application:
    name: EscenaLocal
  datasource:
    url: jdbc:postgresql://localhost:5432/escenadb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 470f26fce7817e
    password: 5a74250b2a0cfb


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        dll-auto: update
    show-sql: true


server:
  port:  8080

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE
        type:
          descriptor:
            sql: TRACE

jwt:
  secret: bXlTZWNyZXRLZXkxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=

  expiration: 86400000  
  refreshExpiration: 1209600000 
mercadopago:
  public-key: TEST-4d19c6e3-1755-4fd7-bdd1-caafb85cb62e
  access-token: TEST-322033363091622-101020-39222800df17823accd071f661d894bb-1465029993
  webhook-secret: 4d936278f2c3885150352d3527788fa1f0d31ecda2e4ca4ba0f4a733b41b1f3c
  enable-webhook: true



